/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion (void);
GtkWidget* create_menu (void);
GtkWidget* create_ajoutermenu (void);
GtkWidget* create_modifiermenu (void);
GtkWidget* create_recherchemenu (void);
GtkWidget* create_meilleur_menu (void);
GtkWidget* create_gestioncapt (void);
GtkWidget* create_window_gestion (void);
GtkWidget* create_window_ajout (void);
GtkWidget* create_window_modification (void);
GtkWidget* create_window_affichage (void);
GtkWidget* create_confirmer_supprission (void);
GtkWidget* create_confirmer_modification (void);
GtkWidget* create_window_quitter (void);
GtkWidget* create_smart_esprit (void);
GtkWidget* create_confirmer_acceuil (void);
